# Generated by Django 5.0.2 on 2025-05-11 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),  # noqa: E501
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="タイトル")),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "未着手"),
                            ("in_progress", "進行中"),
                            ("done", "完了"),
                        ],
                        default="todo",
                        max_length=20,
                        verbose_name="状態",
                    ),
                ),  # noqa: E501
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="期限"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),  # noqa: E501
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),  # noqa: E501
            ],
            options={
                "verbose_name": "タスク",
                "verbose_name_plural": "タスク",
                "ordering": ["-created_at"],
            },
        ),
    ]
