name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      POSTGRES_PORT: 5433  # CI環境用のポート番号
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker images
      run: docker compose build

    - name: Run migrations
      run: docker compose run --rm web python manage.py migrate

    - name: Run tests
      run: docker compose run --rm web pytest

    - name: Run black
      run: docker compose run --rm web black . --check

    - name: Run flake8
      run: docker compose run --rm web flake8 .

    - name: Run isort
      run: docker compose run --rm web isort . --check-only

    - name: Run mypy
      run: docker compose run --rm web mypy . 